# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0ed94b048e6dd1c36be99aef16446b3d7ff0843743a090b7c8bdf579e33816c04a70f82e959f470845bb8401f4cb001d42661255aa9217d740dd0afff054dc

test:
  secret_key_base: ccde06c609b758fc1517c6540442f4a4c819b111c85cbabaaf18b8c6aad9449bbc49be4863b1ace239544083025da9fc35f346397636644e347150bfe87d6e2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
